### ISSUE TITLE
RGB images

### ISSUE THREAD

**Issue by ajwood** [BIC-MNI/Display#49]
Display used to be able to open RGB volumes, if the fastest-varying vector_dimension contains RGB triples (on the range 0-1), but this doesn't seem to work with the latest version.

Is there any change that this feature could come back? Or alternatively, is there a different way to open RGB volumes in Display?

**Comment by rdvincent** [comment]
It wasn't taken out on purpose - I'll figure out what happened and fix it.

**Comment by rdvincent** [comment]
@ajwood Should be fixed if you check out the latest libminc and bicpl. I also make a minor change to Display that formats the RGB value of the current voxel.

**Comment by ajwood** [comment]
@rdvincent Something's still not quite right. Here's the volume sampling:

        dimension name         length         step        start
        --------------         ------         ----        -----
        yspace                      1          0.1         -4.3
        zspace                   1697     -0.00286       10.351
        xspace                   2477      0.00286        2.717
        vector_dimension            3            1            0

Here's what I get when I open it:

    Error inputting global.
    Variable name is Progress_threshold 
    Error inputting global.
    Variable name is Maximum_display_time 
    Error inputting global.
    Variable name is Interval_of_check 
    Error inputting global.
    Variable name is Unfinished_flag_colour 
    Error inputting global.
    Variable name is Unfinished_flag_width 
    Input  rgb.mnc
    Error: MINC file has only 3 dims, volume requires 4.
    Error loading rgb.mnc

I'm on the release-1.0.08 tag of minc-toolkit, with the develop branches of libminc and bicpl.

**Comment by ajwood** [comment]
Looks great! I'm wondering, do you think it'd be tricky to get trilinear or tricubic interpolation working?

**Comment by rdvincent** [comment]
@ajwood I assume you mean trilinear/tricubic with RGB. It's probably not that tricky. How useful would it actually be?

**Comment by ajwood** [comment]
@rdvincent Right; I mean trilinear/tricubic interpolation for RGB slices (from the menu: volume config (Q) -> interp (S)). Currently it shows the interpolant changing, but doesn't actually affect the display.

Do you think it'd be less useful for RGB than it is for intensity images?

**Comment by rdvincent** [comment]
@ajwood I don't really have an opinion - I'm just trying to get a general sense of the priority.

**Comment by ajwood** [comment]
@rdvincent My main uses are this:

[Digital microscopy](https://en.wikipedia.org/wiki/Luxol_fast_blue_stain#/media/File:Coronal_section_of_a_mouse_brain_stained_with_Hematoxylin_%26_LFB.jpg): Interpolation mainly useful for zooming and collecting snapshots.

[DTI colour maps](https://en.wikipedia.org/wiki/Diffusion_MRI#/media/File:Illus_dti.gif): Interpolation helpful when the maps are noisy.

I also wonder about visualizing deformation fields coming out of minctracc (or other registration tools) in Display. Not sure what this would look like, or how it'd play with the different interpolants.

Other people might have different thoughts.

**Comment by rdvincent** [comment]
@ajwood I'll look into it in any case. Do you have any appropriate images available that I can use for testing.

**Comment by ajwood** [comment]
Sure, here's a [dti map](https://drive.google.com/open?id=0BzcZlhs8X1gFWE9kQmE0clEzS0E).

**Comment by gdevenyi** [comment]
I have a related request in #15 to be able to do additive RGB with multiple volumes, but in that case I'm hoping for independent adjustment of the colourmaps for each volume.

In general the idea here is to experiment with "hybrid contrast" for our segmenters, in the hopes of improving tissue differentiation.

**Comment by rdvincent** [comment]
@ajwood I recently added trilinear interpolation for RGB. Tricubic is harder because of implementation details in the volume_io library.

**Comment by ajwood** [comment]
I just noticed that the segmentation painting threshold doesn't work for RGB data.  Would there be an easy fix for this?  e.g. threshold on the mean intensity
